# permissions for end users to view antreainstalls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: antreainstall-viewer-role
rules:
- apiGroups:
  - operator.antrea.vmware.com
  resources:
  - antreainstalls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.antrea.vmware.com
  resources:
  - antreainstalls/status
  verbs:
  - get
