apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: antrea-operator
  namespace: antrea-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: antrea-operator
subjects:
- kind: ServiceAccount
  name: antrea-operator
  namespace: antrea-operator
