apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: antrea-operator
rules:
- apiGroups: [""]
  resources: [endpoints]
  verbs: [get, list, watch]
- apiGroups: [""]
  resources: [pods, configmaps, namespaces, serviceaccounts, secrets, services]
  verbs: [create, get, list, patch, delete, update, watch, deletecollection]
- apiGroups: [apps]
  resources: [deployments, daemonsets]
  verbs: [create, get, list, patch, delete, update, watch]
- apiGroups: [admissionregistration.k8s.io]
  resources: [mutatingwebhookconfigurations, validatingwebhookconfigurations]
  verbs: [get, update, create]
- apiGroups: [apiextensions.k8s.io]
  resources: [customresourcedefinitions]
  verbs: [create, get, list, patch, update, watch, delete]
- apiGroups: [discovery.k8s.io]
  resources: [endpointslices]
  verbs: [get, watch, list]
- apiGroups: [rbac.authorization.k8s.io]
  resources: [clusterroles, clusterrolebindings]
  verbs: [create, get, list, patch, update, watch, delete]
- apiGroups: [config.openshift.io]
  resources: [clusteroperators]
  verbs: [create, get, list, patch, update, watch, delete]
- apiGroups: [config.openshift.io]
  resources: [clusteroperators/status]
  verbs: [get, patch, update]
- apiGroups: [config.openshift.io]
  resources: [networks, networks/finalizers]
  verbs: [get, list, watch, patch, update]
- apiGroups: [operator.openshift.io]
  resources: [networks]
  verbs: [get, list, watch, patch, update]
- apiGroups: [operator.antrea.vmware.com]
  resources: [antreainstalls, antreainstalls/status]
  verbs: [get, list, watch, create,patch, update]
# Required by antrea-agent, antrea-controller and antctl
- apiGroups: [""]
  resources: [nodes]
  verbs: [get, watch, list, patch]
- apiGroups: [""]
  resources: [pods, endpoints]
  verbs: [get, watch, list, delete]
- apiGroups: [authentication.k8s.io]
  resources: [tokenreviews]
  verbs: [create]
- apiGroups: [authorization.k8s.io]
  resources: [subjectaccessreviews]
  verbs: [create]
- apiGroups: [apiregistration.k8s.io]
  resources: [apiservices]
  verbs: [get, create, update, delete]
- apiGroups: [controlplane.antrea.tanzu.vmware.com]
  resources: [networkpolicies, appliedtogroups, addressgroups]
  verbs: [get, list, watch]
- apiGroups: [controlplane.antrea.tanzu.vmware.com]
  resources: [nodestatssummaries]
  verbs: [create]
- apiGroups: [controlplane.antrea.tanzu.vmware.com]
  resources: [networkpolicies/status]
  verbs: [create, get]
- apiGroups: [core.antrea.tanzu.vmware.com]
  resources: [clustergroups]
  verbs: [get, create, update, delete, list, watch, patch]
- apiGroups: [core.antrea.tanzu.vmware.com]
  resources: [externalentities]
  verbs: [get, watch, list]
- apiGroups: [core.antrea.tanzu.vmware.com]
  resources: [clustergroups/status]
  verbs: [update]
- apiGroups: [networking.k8s.io]
  resources: [networkpolicies]
  verbs: [get, watch, list]
- apiGroups: [ops.antrea.tanzu.vmware.com]
  resources: [traceflows, traceflows/status]
  verbs: [create, get, list, patch, update, watch, delete, delete]
- apiGroups: [clusterinformation.antrea.tanzu.vmware.com]
  resources: [antreaagentinfos, antreacontrollerinfos]
  verbs: [get, list, create, update, delete, delete]
- apiGroups: [networking.antrea.tanzu.vmware.com]
  resources: [networkpolicies, appliedtogroups, addressgroups]
  verbs: [get, watch, list, delete]
- apiGroups: [security.antrea.tanzu.vmware.com]
  resources: [clusternetworkpolicies, networkpolicies]
  verbs: [get, create, update, delete, list, watch, patch]
- apiGroups: [security.antrea.tanzu.vmware.com]
  resources: [clusternetworkpolicies/status, networkpolicies/status]
  verbs: [update]
- apiGroups: [security.antrea.tanzu.vmware.com]
  resources: [tiers]
  verbs: [get, watch, list, create, update]
- apiGroups: [stats.antrea.tanzu.vmware.com]
  resources: [networkpolicystats, antreaclusternetworkpolicystats, antreanetworkpolicystats]
  verbs: [get, list]
- apiGroups: [system.antrea.tanzu.vmware.com]
  resources: [controllerinfos, agentinfos, supportbundles, supportbundles/download]
  verbs: [get, watch, list, post, delete]
- apiGroups: [security.openshift.io]
  resourceNames: [hostnetwork]
  resources: [securitycontextconstraints]
  verbs: [use]
- nonResourceURLs:
  - /agentinfo
  - /addressgroups
  - /appliedtogroups
  - /loglevel
  - /networkpolicies
  - /ovsflows
  - /ovstracing
  - /podinterfaces
  verbs:
  - get
