name: Generate manifests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate manifests
        run: make manifests
      - name: Check for any unexpected changes
        run: |
          diff="$(git status --porcelain)"
          if [ ! -z "$diff" ]; then
              >&2 echo "The generated code is not up-to-date"
              >&2 echo "The different files are:"
              >&2 echo "$diff"
              >&2 echo "You can regenerate files locally with 'make manifests', and commit the changes"
              exit 1
          fi
